### ISSUE TITLE
Bookmark don't show icons.

### ISSUE THREAD

**Issue by CREATORCorp** [akkva/WhiteSur-firefox-theme-monterey#2]
Hi! Nice, clean, simple and good theme i think. Only problem i found is this thing, i use always bookmark without name, just icons and there is a problem because they don't show. And maybe you can do a english description. Thx for theme!

**Comment by akkva** [comment]
你好！要显示书签图标删除图片中标红的代码即可^_^
<br>
<img width="1160" alt="0210" src="https://github.com/akkva/WhiteSur-firefox-theme-monterey/assets/150437642/7903774e-a47e-4bde-935d-144895f1a877">
