### ISSUE TITLE
Flickering tabs.

### ISSUE THREAD

**Issue by CREATORCorp** [akkva/WhiteSur-firefox-theme-monterey#3]
Hello! is not from that version. Is from the older one but keep persist. Sometimes, when u make a windows smaller, not fullscreen and u have more tabs they make a odd flickering hard to fix. Keep good theme overall. Gj!

**Comment by akkva** [comment]
你好！是mac还是win？你可以用默认主题试一下，是不是有相同的问题，方便的话贴一下视频或截图

**Comment by CREATORCorp** [comment]
Windows 11
