### ISSUE TITLE
Small issue with scrolling on tabs

### ISSUE THREAD

**Issue by drkhero** [akkva/WhiteSur-firefox-theme-monterey#4]
First of all, congratulations with this theme - this is by far the best theme I've used so far for Firefox and I absolutely love the design. This is perfect. 10/10 :)

Only issue is when I try scrolling in tabs, it's not smooth, and won't let me scroll all the way on the top tabs most of the time. Trying to scroll on tabs is very glitchy and I have to use the arrows for it to properly work.

I'm using a MacBook Pro 16" on the latest firefox version.

**Comment by akkva** [comment]
你好，这个问题已经找到方法修复了，马上会发新版，感谢喜欢！

**Comment by drkhero** [comment]
> 你好，这个问题已经找到方法修复了，马上会发新版，感谢喜欢！
> 
> 你可以先下载[toolbox.css](https://github.com/akkva/WhiteSur-firefox-theme-monterey/raw/main/chrome/Monterey/parts/toolbox.css)替换`chrome/Monterey/parts`内的同名文件测试下

Thank you! It works perfectly now ✅
