### ISSUE TITLE
Check box too small

### ISSUE THREAD

**Issue by jorgehezd** [akkva/WhiteSur-firefox-theme-monterey#5]
Hi, first at all thanks so much for the theme. It's really beautiful.

I have an little issue in some webpages, I attach screenshot:

<img width="86" alt="Screenshot 2024-02-15 at 11 46 28" src="https://github.com/akkva/WhiteSur-firefox-theme-monterey/assets/94623596/6c235d7f-17d3-463b-9b94-43eae565c5e3">

Here, I can chosse an item but I can't see when I select it.

<img width="276" alt="Screenshot 2024-02-15 at 11 47 17" src="https://github.com/akkva/WhiteSur-firefox-theme-monterey/assets/94623596/1e71e67d-e172-47bf-83c1-428851e7fd7e">

Same here, I can choose an option.

<img width="163" alt="Screenshot 2024-02-15 at 11 47 33" src="https://github.com/akkva/WhiteSur-firefox-theme-monterey/assets/94623596/c4aab822-81ef-4bfb-8f3a-d1791c4c0ffe">

And here, I've selected the first option.

**Comment by akkva** [comment]
你好！可以贴一下网址吗？

**Comment by jorgehezd** [comment]
Thanks so much. It works fine. Great job @akkva
