### ISSUE TITLE
Can't see full URL when hovering on top box

### ISSUE THREAD

**Issue by drkhero** [akkva/WhiteSur-firefox-theme-monterey#6]
When I hover over the URL with my mouse, the box will shrink instead of expanding, which means I can't see the full URL. Also, when I start typing or editing the URL, there's so much blur I'm unable to see what I'm typing. So very hard to type long URLs or Google searches.

And finally, is there a way to make it so that every tab always shows the icon of the webpage ?

Thank you !

**Comment by akkva** [comment]
标签页图标：
<img width="1131" alt="d1" src="https://github.com/akkva/WhiteSur-firefox-theme-monterey/assets/150437642/e45c4e24-ac5f-48eb-a62e-8b6379330f8b">
网址模糊：
<img width="737" alt="d2" src="https://github.com/akkva/WhiteSur-firefox-theme-monterey/assets/150437642/5cf00ec0-5173-47a0-9753-d2f8c812ea70">

**Comment by drkhero** [comment]
Amazing! Everything is working perfect apart from this small issue when there's sound coming from a tab:
<img width="318" alt="Screen Shot 2024-02-17 at 8 20 11 AM" src="https://github.com/akkva/WhiteSur-firefox-theme-monterey/assets/155139404/6661e130-d8b2-4408-8944-92c44dba0e86">

**Comment by akkva** [comment]
> Amazing! Everything is working perfect apart from this small issue when there's sound coming from a tab: <img alt="Screen Shot 2024-02-17 at 8 20 11 AM" width="318" src="https://private-user-images.githubusercontent.com/155139404/305645893-6661e130-d8b2-4408-8944-92c44dba0e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzgzNTQsIm5iZiI6MTcwODE3ODA1NCwicGF0aCI6Ii8xNTUxMzk0MDQvMzA1NjQ1ODkzLTY2NjFlMTMwLWQ4YjItNDQwOC04OTQ0LTkyYzQ0ZGJhMGU4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxMzU0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTEzYmQ3ODE2ZWEyNjAxODAyZTkwMjUwM2MxYjM1MTVjNzllMmJiNjEyZjE4MTJiYzM3NjY1YmIxYzE3ZTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XQoSYz3KUYU3eAv5-6p6a5UUA53N_z0MhNiitAi46HE">

`.tabbrowser-tab:is([soundplaying], [muted], [activemedia-blocked]) .tab-icon-image {
  display: none !important;
}`

把这段加回去
