### ISSUE TITLE
Your theme is very nice

### ISSUE THREAD

**Issue by safak45xx** [akkva/WhiteSur-firefox-theme-monterey#7]
I made a change on the theme, I want to share a github sharing if you permission
[chrome.zip](https://github.com/akkva/WhiteSur-firefox-theme-monterey/files/14316914/chrome.zip)

**Comment by akkva** [comment]
谢谢分享！

**Comment by safak45xx** [comment]
https://github.com/safak45xx/Blurfox-MacOS-

**Comment by safak45xx** [comment]
I hope you like it. I'm new to CSS, and thanks to you, I managed to create the theme I wanted.
